---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tradisanalyseR

<!-- badges: start -->
<!-- badges: end -->

tradisanalyseR was developed as a collection of scripts to further analyse output produced by the Bio-TraDIS toolkit (https://github.com/sanger-pathogens/Bio-Tradis). It takes the resulting csv files for any number of conditions and formats it for use in these scripts.
This is a work-in-progress. Please email Geri at geraldine.sullivan@hdr.mq.edu.au if you have any reproducibility issues.

## Scripts
### structure_csv()
Takes all csv files from a folder and combines them into one data table for visualisation and further processing.

### logfc_plots()
Using the structure_csv() output and a gene list, plots log fold changes for those genes over all conditions in one graph.

### 

## Installation

<!-- You can install the released version of tradisanalyseR from  [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("tradisanalyseR")
```
-->
The development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("gerisullivan/tradisanalyseR")
```

tradisanalyseR has the following dependencies:
```r
dplyr
EDASeq (>= 2.24.0)
ggplot2
ggseqlogo
gridExtra
msa
purrr
reshape2
RUVSeq
RWebLogo
seqinr
stats
stringr
```
